### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by ThomasKoscheck** [jestillore/wakatimejs#3]
Hey,
I really like your project! Maybe you could consider to add some basic examples? Maybe on just how to get some data and export them in file?

I would really appreciate this!

**Comment by jestillore** [comment]
Usage instructions are already in the README.
To get some data and export them to a file, you have to, first, fetch the required data. You can do it like this,
```
wi.summaries({
    start: '2015-10-07',
    end: '2015-10-13'
}, function (error, response, summary) {
    // write your code to export summary object to a file here
});
```
