### ISSUE TITLE
Out of date? (NO)

### ISSUE THREAD

**Issue by TheAlexLichter** [jestillore/wakatimejs#4]
This JS lib is unfortunately out of date. WakaTime now uses [OAuth2](https://wakatime.com/developers#authentication) for Authentication.

**EDIT:** It still works with using the API key. Nvm ☺️

**Comment by jestillore** [comment]
Oh. Thank you for the heads up :)
Will update this library when I have a time.

**Comment by TheAlexLichter** [comment]
No no, it's fine. The only thing is updating the library to ES6/ES5. I'm working on it ☺️
